import { ColumnDef } from "@tanstack/react-table";
import { CustomReportRow } from "../types";
import { Button } from "@/components/ui/button";
import StatusBadge from "@/components/shared/common-status-badge";
import {
  Download,
  FileBarChartIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
} from "lucide-react";
import { ReportFormat } from "@/data/app.data";
import { JSX } from "react";

// Mapping of format → icon + label
export const formatMap: Record<
  ReportFormat,
  { icon: JSX.Element; label: string }
> = {
  [ReportFormat.PDF]: {
    icon: <FileTextIcon className="w-4 h-4 text-red-500" />,
    label: "PDF",
  },
  [ReportFormat.EXCEL]: {
    icon: <FileSpreadsheetIcon className="w-4 h-4 text-green-500" />,
    label: "Excel",
  },
  [ReportFormat.CSV]: {
    icon: <FileBarChartIcon className="w-4 h-4 text-blue-500" />,
    label: "CSV",
  },
};

export const customReportsColumns: ColumnDef<CustomReportRow>[] = [
  {
    accessorKey: "type",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="hover:bg-transparent p-0 font-semibold"
        >
          Type{" "}
        </Button>
      );
    },
  },
  {
    accessorKey: "generatedBy",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="hover:bg-transparent p-0 font-semibold"
        >
          Generated By
        </Button>
      );
    },
  },
  {
    accessorKey: "date",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="hover:bg-transparent p-0 font-semibold"
        >
          Date
        </Button>
      );
    },
    cell: ({ row }) => (
      <div>
        {row.getValue("date") as string}
        <br />
        <span className="text-sm text-muted-foreground">
          {row.original.time}
        </span>
      </div>
    ),
  },
  {
    accessorKey: "format",
    header: "Format",
    cell: ({ row }) => {
      const format = row.getValue("format") as ReportFormat;
      const formatData = formatMap[format];

      if (!formatData) return <span>-</span>;

      return (
        <div className="flex items-center gap-2">
          {formatData.icon}
          <span className="font-medium">{formatData.label}</span>
        </div>
      );
    },
  },
  {
    accessorKey: "size",
    header: ({ column }) => {
      return (
        <Button
          variant="ghost"
          onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
          className="hover:bg-transparent p-0 font-semibold"
        >
          Size{" "}
        </Button>
      );
    },
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      const status = row.getValue("status");
      return <StatusBadge status={status as any} />;
    },
  },
  {
    id: "actions",
    header: "Actions",
    cell: () => (
      <div className="flex space-x-2">
        <Button size="sm" variant="outline">
          <Download className="h-4 w-4" />
        </Button>
      </div>
    ),
  },
];
