import { ColumnDef } from "@tanstack/react-table";
import { CustomReportRow } from "../types";
import { Button } from "@/components/ui/button";
import StatusBadge from "@/components/shared/common-status-badge";
import {
  Download,
  FileBarChartIcon,
  FileSpreadsheetIcon,
  FileTextIcon,
} from "lucide-react";
import { REPORT_FORMAT } from "@/data/app.data";
import { JSX } from "react";
import { CustomDataTableColumnHeader } from "@/components/shared/custom-table-header-column";
import { format } from "date-fns";
import { formatFileSize } from "@/utils/commonFunction";

// Mapping of format → icon + label
export const formatMap: Record<
  REPORT_FORMAT,
  { icon: JSX.Element; label: string }
> = {
  [REPORT_FORMAT.PDF]: {
    icon: <FileTextIcon className="w-4 h-4 text-red-500" />,
    label: "PDF",
  },
  [REPORT_FORMAT.EXCEL]: {
    icon: <FileSpreadsheetIcon className="w-4 h-4 text-green-500" />,
    label: "Excel",
  },
  [REPORT_FORMAT.CSV]: {
    icon: <FileBarChartIcon className="w-4 h-4 text-blue-500" />,
    label: "CSV",
  },
};

export const reportsHistoryColumns: ColumnDef<CustomReportRow>[] = [
  {
    accessorKey: "type",
    header: ({ column }) => (
      <CustomDataTableColumnHeader column={column} title="Type" />
    ),
    enableHiding: false,
    enableSorting: false,
  },
  {
    header: "Generated By",
    accessorKey: "createdByData",
    cell: ({ row }) => {
      const data = row.original.createdByData;
      return `${data.firstName || ""} ${data.lastName || ""}`.trim();
    },
  },
  {
    header: "Date",
    accessorKey: "createdDate",
    cell: ({ row }) => {
      const date = new Date(row.original.createdDate);
      return format(date, "dd-MM-yyyy");
    },
  },
  {
    accessorKey: "format",
    header: ({ column }) => (
      <CustomDataTableColumnHeader column={column} title="Format" />
    ),
    enableHiding: false,
    enableSorting: false,
  },
  {
    accessorKey: "fileSize",
    header: ({ column }) => (
      <CustomDataTableColumnHeader column={column} title="Size" />
    ),
    enableHiding: false,
    enableSorting: false,
    cell: ({ row }) => {
      return formatFileSize(Number(row.original.fileSize));
    },
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => {
      const status = row.getValue("status");
      return <StatusBadge status={status as any} />;
    },
  },
  {
    header: "Action",
    accessorKey: "fileUrl",
    cell: ({ row }) => {
      const url = row.original.fileUrl;
      return (
        <Button size="sm" variant="outline" disabled={!url}>
          <a href={url} target="_blank" rel="noopener noreferrer">
            <Download className="h-4 w-4" />
          </a>
        </Button>
      );
    },
  },
];
