import { z } from "zod";

export const workingHourSchema = z.object({
  day: z.number().min(0).max(6),
  start_time: z.string(),
  end_time: z.string(),
  is_closed: z.boolean(),
});

export const merchantSchema = z.object({
  name: z.string().min(1, "Full Name is required"),
  user_name: z.string().min(1, "Username is required"),
  merchant_id: z.string().min(1, "Merchant ID is required"),
  email: z.string().email("Invalid email address").min(1, "Email is required"),
  mobile: z.string().optional(),
  gender: z.enum(["male", "female", "other"]).optional().default("male"),
  password: z.string().min(8, "Password must be at least 8 characters"),
  language: z.string().optional(),
  country_code: z.string().optional().default("+1"),
  country: z.string().optional().default("US"),
  login_type: z.string().optional().default("normal"),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip_code: z.string().optional(),
  tax_id: z.string().optional(),
  support_email: z.string().email("Invalid support email").optional().or(z.literal("")),
  currency: z.string().optional().default("USD"),
  invoice_no_without_ncf: z.string().optional(),
  invoice_no_with_ncf: z.string().optional(),
  payment_no_without_ncf: z.string().optional(),
  payment_no_with_ncf: z.string().optional(),
  plan: z.enum(["Basic", "Pro", "Enterprise"]).optional().default("Basic"),
  industry_type: z.string().optional(),
  online_store_url: z.string().optional(),
  online_store_location: z.string().optional(),
  desktop_name: z.string().optional(),
  doing_business_as: z.string().optional(),
  nif: z.string().optional(),
  instagram: z.string().optional(),
  whatsapp: z.string().optional(),
  facebook: z.string().optional(),
  twitter: z.string().optional(),
  reg_dgii: z.string().optional(),
  description: z.string().optional(),
  invoice_public_url: z.string().optional(),
  signature_image: z.instanceof(File).nullable().optional(),
  store_theme_background_image: z.instanceof(File).nullable().optional(),
  store_background_image: z.instanceof(File).nullable().optional(),
  logo_image: z.instanceof(File).nullable().optional(),
  profile_picture: z.instanceof(File).nullable().optional(),
  working_hours: z.array(workingHourSchema).length(7),
});

// Type for form data
export type MerchantFormData = z.infer<typeof merchantSchema>;

// Default values
export const defaultValues: MerchantFormData = {
  name: "",
  user_name: "",
  merchant_id: "",
  email: "",
  mobile: "",
  gender: "male",
  password: "",
  language: "",
  country_code: "+1",
  country: "US",
  login_type: "normal",
  address: "",
  city: "",
  state: "",
  zip_code: "",
  tax_id: "",
  support_email: "",
  currency: "USD",
  invoice_no_without_ncf: "",
  invoice_no_with_ncf: "",
  payment_no_without_ncf: "",
  payment_no_with_ncf: "",
  plan: "Basic",
  industry_type: "",
  online_store_url: "",
  online_store_location: "",
  desktop_name: "",
  doing_business_as: "",
  nif: "",
  instagram: "",
  whatsapp: "",
  facebook: "",
  twitter: "",
  reg_dgii: "",
  description: "",
  invoice_public_url: "",
  signature_image: null,
  store_theme_background_image: null,
  store_background_image: null,
  logo_image: null,
  profile_picture: null,
  working_hours: [
    { day: 0, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 1, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 2, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 3, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 4, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 5, start_time: "10:00", end_time: "18:00", is_closed: false },
    { day: 6, start_time: "10:00", end_time: "18:00", is_closed: false },
  ],
};
export const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
