const API = {
  auth: {
    login: "auth/admin/login",
    sendOtp: "auth/sendOtp",
    adminLogin: "auth/adminLogin",
    superAdminLogin: "auth/superAdminlogin",
    getUserByToken: "auth/getUserByToken",
    signup: "auth/signup",
    getDepartment: "department/list",
    organizationTypes: "organizationType/list",
    setPassword: "auth/changePassword",
    forgotPassword: "auth/forgot-password",
    resetPassword: "auth/reset-password",
    getPermissions: "auth/getPermissions",
  },
  category: {
    list: "expensesCategory/list",
    create: "expensesCategory/create",
    delete: "expensesCategory/delete",
    update: "expensesCategory/patch",
  },
  expenseCategories: {
    list: "expenseCategory/list",
    create: "expenseCategory/create",
    update: "expenseCategory/patch",
    delete: "expenseCategory/delete",
    perDiemSettings: "expenseCategory/per-diem-settings/update",
    settings: "expenseCategory/settings/update",
  },
  liveTracking: {
    list: "liveTracking/list",
    user: "users",
    getWorkDaySession: "workDaySession/getSession",
    visitAnalytics: "visit/analytics",
    userTracking: "user-tracking/user",
    userList: "users/list",
  },
  customerType: {
    list: "customerType/list",
    create: "customerType/create",
    update: "customerType/patch",
    delete: "customerType/delete",
  },
  customerMain: {
    list: "customer/list",
    getCustomerById: "customer",
    create: "customer/create",
    createSingle: "customer/create-single",
    update: "customer/patch",
    delete: "customer/delete",
    statusCounts: "customer/status-counts",
    pendingList: "customer/status-pending-list",
    updateStatus: "customer/update-status",
    importCsv: "customer/import/csv",
    exportCsv: "customer/export/csv",
    exportExcel: "customer/export/xlsx",
  },
  merchants: {
    list: "merchant/list",
    create: "merchant/add-merchant",
    update: "merchant/update",
    delete: "merchant/delete",
    details: "merchant/detail",
    getWorkingHours: "merchant/working-hours/list",
    updateWorkingHours: "merchant/working-hours",
  },
  organizations: {
    list: "organization/list",
    create: "organization/create",
    update: "organization/patch",
    delete: "organization/delete",
    details: "organization/detail",
    getWorkingHours: "merchant/working-hours/list",
    updateWorkingHours: "merchant/working-hours",
    statusCounts: "organization/analytics",
    pendingAdmins: "users/all",
    AllUsers: "users/all",
    updateStatus: "auth/activeDeactivateUserBySuperAdmin",
  },

  employeeRange: {
    list: "employeeRang/list",
    create: "employeeRang/create",
    update: "employeeRang/patch",
    delete: "employeeRange/delete",
  },
  industry: {
    list: "industry/list",
    create: "industry/create",
    update: "industry/patch",
  },
  menu: {
    list: "menu/list",
    create: "menu/create",
    update: "menu/patch",
  },
  users: {
    list: "users/list",
    create: "users/create",
    update: "users/patch",
    delete: "users/delete",
    stats: "users/stats",
  },
  roles: {
    list: "role/list",
    create: "role/create",
    update: "role/patch",
    delete: "roles/delete",
    details: "roles/details",
    permissions: "permission/list",
    getAllPermissions: "role",
    organizationMenulist: "organizationMenu/list",
  },
  overview: {
    stats: "overview/stats",
    salesReps: "overview/sales-reps",
    activities: "overview/activities",
    performance: "overview/performance",
    updateStatus: "overview/update-status",
    exportReport: "overview/export-report",
    auditLogList: "auditLog/all",
  },
  territories: {
    list: "userTerritory/list",
    create: "userTerritory/create",
    update: "userTerritory/patch",
    delete: "userTerritory/delete",
  },
  calendar: {
    visitList: "visit/list",
    create: "visit/create",
    update: "visit/patch",
    analytics: "visit/analytics",
    getVisitByID: "visit",
    delete: "visit/delete",
    visitFeedBack: "visit/visitFeedBack",
    visitEmployeeAnalytics: "visit/visitEmployeeAnalytics",
  },
  dailyExpenses: {
    list: "expenses/list",
    getById: "expenses",
    expenseReviewAndApproval: "expenseReviewAndApproval/create",
    expenseReviewAndApprovalMultiple:
      "expenseReviewAndApproval/create-multiple",
    expenseReviewAndApprovalUpdate: "expenseReviewAndApproval/patch",
    delete: "expenses/delete",
  },
  customer: {
    customerList: "customer/list",
  },
  drivers: {
    list: "driver/list",
    create: "driver/add-driver",
    update: "driver/update",
    delete: "driver/delete",
    details: "driver/driver-documents",
  },
  documents: {
    list: "document/list",
    create: "document/create",
    update: "document/update",
    delete: "document/delete",
  },
  notifications: {
    list: "notification/list",
    create: "notification/create",
    update: "notification/update",
    delete: "notification/delete",
    details: "notification/detail",
    sendNotification: "notification/send",
    unreadCount: "notification/unreadNotificationCount",
  },
  settings: {
    list: "settings/list",
    create: "settings/create",
    update: "settings/update",
    delete: "settings/delete",
    details: "settings/detail",
  },
  Expenses: {
    consolidated: "expenses/monthly-consolidated",
    list: "expenses/monthly-expenses/list",
    getById: "expenses/monthly-expenses",
    listDetailed: "expenses/list/detailed",
  },
  ExpenseAnalytics: {
    list: "expenses/approvals/analytics",
  },
  approvals: {
    lists: "approvals/list",
    action: "approvals/action",
    stats: "approvals/stats",
    workflows: "approval-workflows",
    list: "expenseApprovalLevel/list",
    create: "expenseApprovalLevel/create",
    update: "expenseApprovalLevel/patch",
    delete: "expenseApprovalLevel/multi-delete",
    organizationCreate: "organization/patch",
    tierList: "users/tiers/list",
  },
  fixedDayExpense: {
    list: "fixedDayExpense/list",
    create: "fixedDayExpense/create-multiple",
    update: "fixedDayExpense/update-multiple",
    delete: "fixedDayExpense/delete-multiple",
  },
  generalSettings: {
    list: "generalSettings/list",
    get: "generalSettings/get",
    create: "generalSettings/create",
    updateCompanyInfo: "generalSettings/company-info",
    updateSystemPreferences: "generalSettings/system-preferences",
    companyInfo: "generalSettings/company-info",
    systemPreferences: "generalSettings/system-preferences",
  },
  expenseLimit: {
    list: "expenseLimit/list",
    create: "expenseLimit/create",
    update: "expenseLimit/patch",
    delete: "expenseLimit/delete",
  },
  notificationSettings: {
    get: "notification-configuration",
    update: "notification-configuration",
  },
  reports: {
    expanseReport: "expenseReport/generate",
    customeReport: "customReport/generate",
    list: "report/list",
    create: "report/create",
    createExpanseReport: "report/expenseReportCreate",
    customReportList: "report/type/list",
  },
  termsAndConditions: {
    list: "termsAndConditions/list",
    create: "termsAndConditions/create",
    update: "termsAndConditions/update",
    delete: "termsAndConditions/delete",
    getTerms: "termsAndConditions/active",
  },
  leaveType: {
    list: "leaveType/list",
    create: "leaveType/create",
    update: "leaveType/patch",
    delete: "leaveType/delete",
    stats: "leaveType/stats",
  },
  leaveRulesConfig: {
    list: "leave-rule-configuration",
    update: "leave-rule-configuration",
  },
  holidayTemplate: {
    list: "holiday-template/list",
    create: "holiday-template/create",
    update: "holiday-template/patch",
    delete: "holiday-template/delete",
    stats: "holiday-template/stats",
  },
  holiday: {
    byId: "holiday",
    list: "holiday/list",
    create: "holiday/create",
    update: "holiday/patch",
    delete: "holiday/delete",
  },
  employeeTier: {
    list: "user-tiers/list",
    create: "user-tiers/create",
    update: "user-tiers/patch",
    delete: "user-tiers/delete",
    stats: "user-tiers/stats",
  },
  leave: {
    byId: "leave",
    list: "leave/list",
    myLeave: "leave/my",
    create: "leave/create",
    update: "leave/patch",
    delete: "leave/delete",
    stats: "leave/stats",
  },
};

Object.freeze(API);

export default API;
